### PR TITLE
Added trailing zeroes when focus is changed in decimal mode.

### PR DESCRIPTION
**Pull request by akkshaylawrence**
Added trailing zeroes on blur when typing a decimal number in the input.

### CODE REVIEW

**Comment by BaseMax** [comment]
Hello Akkshay,

Thank you very much for your help.

Is it possible to build this project? (`dist/` directory)
https://github.com/BaseMax/FilterInputJs/blob/master/dist/index.min.js

Read more: https://github.com/BaseMax/FilterInputJs/issues/1#issuecomment-507522987

Thank you for contributing to the development of the project.
Regards,

**Comment by BaseMax** [comment]
Can you add unsupported data filters? `data-filter="..."`
https://github.com/BaseMax/FilterInputJs#data-filters

I appreciate you.

**Comment by akkshaylawrence** [comment]
@BaseMax It is getting built successfully but I think we need to separate the config files for dev and prod builds. My IDE is throwing errors like
`Can't analyse webpack.config.js: coding assistance will ignore module resolution rules in this file. Possible reasons: this file is not a valid webpack configuration file or its format is not currently supported by the IDE. Error details:  Cannot read property 'mode' of undefined`

> 
> 
> Hello Akkshay,
> 
> Thank you very much for your help.
> 
> Is it possible to build this project? (`dist/` directory)
> https://github.com/BaseMax/FilterInputJs/blob/master/dist/index.min.js
> 
> Read more: [#1 (comment)](https://github.com/BaseMax/FilterInputJs/issues/1#issuecomment-507522987)
> 
> Thank you for contributing to the development of the project.
> Regards,

**Comment by akkshaylawrence** [comment]
> 
> 
> Can you add unsupported data filters? `data-filter="..."`
> https://github.com/BaseMax/FilterInputJs#data-filters
> 
> I appreciate you.

I will add them as and when I get time 😄

**Pull request closed without merging**
